services:
  - type: web
    name: stock-backend
    env: python
    rootDir: backend-django
    buildCommand: ./build.sh
    startCommand: gunicorn stock_prediction_main.wsgi:application --bind 0.0.0.0:$PORT
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DJANGO_SETTINGS_MODULE
        value: stock_prediction_main.settings
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "stock-backend.onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_BACKEND
        value: django.core.mail.backends.smtp.EmailBackend
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: FRONTEND_BASE_URL
        value: https://your-frontend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: "https://your-frontend.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://stock-backend.onrender.com"
